name: Build Core

on:
  repository_dispatch:
    types: [build-core]

  workflow_dispatch:

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: carbonium-community/carbonium
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build -o ./dist/ github.com/carbonium-community/carbonium

      - uses: actions/upload-artifact@v4
        with:
          name: carbonium
          path: ./dist/carbonium